
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        QUESTION_ADD_NEW : "QUESTION_ADD_NEW",
        QUESTION_ADD_IMPORT : "QUESTION_ADD_IMPORT",
        QUESTION_ADD_MANUAL : "QUESTION_ADD_MANUAL",
        EXAM_PARTIC_IMPORT : "EXAM_PARTIC_IMPORT",
        MODAL_SUCCESS : "MODAL_SUCCESS",
        MODAL_ERROR : "MODAL_ERROR",
        QUESTION_EDIT : "QUESTION_EDIT",
        EXAM_ADD_NEW : "EXAM_ADD_NEW",
        EXAM_EDIT : "EXAM_EDIT",
        SCHEDULE_ADD_NEW : "SCHEDULE_ADD_NEW",
        SCHEDULE_EDIT : "SCHEDULE_EDIT",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        QUESTION_DELETE : "QUESTION_DELETE",
        EXAM_DELETE : "EXAM_DELETE",
        SCHEDULE_DELETE : "SCHEDULE_DELETE",
        LOGIN_SUCCESS : "LOGIN_SUCCESS",
        LOGIN_ERROR : "LOGIN_ERROR",
        EXAM_SUCCESS : "EXAM_SUCCESS",
        EXAM_ERROR : "EXAM_ERROR",
        EXAM_PARTIC_IMPORT_SUCCESS : "EXAM_PARTIC_IMPORT_SUCCESS",
        EXAM_PARTIC_IMPORT_SUCCESS : "EXAM_PARTIC_IMPORT_SUCCESS",
    },
});
